In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

plt.rcParams['font.family'] = 'Malgun Gothic'
# plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['figure.figsize'] = 12, 6
plt.rcParams['font.size'] = 14
plt.rcParams['axes.unicode_minus'] = False

# 데이터 전처리 관련 ################################################
# 결측치 처리
from sklearn.impute import SimpleImputer
# 표준화
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
# 인코더
from sklearn.preprocessing import LabelEncoder
# 원핫 인코더
from sklearn.preprocessing import OneHotEncoder

# 학습 모델 성능 관련 #######################################
# 원하는 비율로 데이터를 나누기 위해
from sklearn.model_selection import train_test_split
# K-Fold 교차 검증
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold
# 학습 곡선
from sklearn.model_selection import learning_curve
# 하이퍼 파라미터 튜닝
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint
import optuna
from optuna.samplers import TPESampler
from optuna.pruners import MedianPruner
optuna.logging.set_verbosity(optuna.logging.WARNING)

# 모델 성능 평가 ########################
# 회귀용
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import root_mean_squared_error
from sklearn.metrics import r2_score
# 분류용
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_curve
from sklearn.metrics import auc
from sklearn.metrics import roc_auc_score
from sklearn.metrics import ConfusionMatrixDisplay

# 피처 선택 #########################
from sklearn.feature_selection import VarianceThreshold
from sklearn.feature_selection import RFE
from sklearn.inspection import permutation_importance

# 학습 모델 ########################
# 분류
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier 
from sklearn.naive_bayes import GaussianNB
from catboost import CatBoostClassifier

# 회귀
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
from lightgbm import LGBMRegressor
from xgboost import XGBRegressor
from sklearn.linear_model import BayesianRidge
from catboost import CatBoostRegressor

# 결정트리를 시각화할 수 있는 라이브러리
from sklearn.tree import plot_tree

# 차원 축소
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.manifold import TSNE

# 연관 규칙 학습
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import fpgrowth
from mlxtend.frequent_patterns import association_rules

# 군집
from sklearn.cluster import KMeans
from sklearn.cluster import DBSCAN
from scipy.cluster.hierarchy import dendrogram, linkage, fcluster
from sklearn.mixture import GaussianMixture
from sklearn.cluster import MeanShift, estimate_bandwidth

# 파이프라인
from sklearn.pipeline import Pipeline

# KDE를 그리기 위한 통계값을 구할 수 있는 함수
from scipy.stats import gaussian_kde

# 피어슨 상관 계수 (연속형 수치형 데이터 vs 연속형 수치형 데이터)
from scipy.stats import pearsonr
# 카이제곱 검증 (범주형 데이터 vs 범주형 데이터, 순위X)
from scipy.stats import chi2_contingency
# 스피어만 상관계수 (범주형 데이터 vs 범주형 데이터, 순위O)
from scipy.stats import spearmanr
# 포인트 이분 상관계수 (범주형 데이터 vs 연속형 수치형 데이터)
from scipy.stats import pointbiserialr

# 객체를 파일에 저장
import pickle

# 불필요한 경고 뜨지 않게
import warnings
warnings.filterwarnings('ignore')

### 데이터를 불러온다.

In [2]:
train_df = pd.read_csv('data/bike_sharing_train5.csv')
train_df

,temp,humidity,log_count,year,log_windspeed,season_1,season_2,season_3,season_4,weather_1,...,hour_14,hour_15,hour_16,hour_17,hour_18,hour_19,hour_20,hour_21,hour_22,hour_23
0,9.84,81,2.833213,1,0.000000,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,9.02,80,3.713572,1,0.000000,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,9.02,80,3.496508,1,0.000000,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,9.84,75,2.639057,1,0.000000,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,9.84,75,0.693147,1,0.000000,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10881,15.58,50,5.820083,0,3.295937,0.0,0.0,0.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
10882,14.76,57,5.488938,0,2.772670,0.0,0.0,0.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
10883,13.94,61,5.129899,0,2.772670,0.0,0.0,0.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
10884,13.94,61,4.867534,0,1.946367,0.0,0.0,0.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
10885,13.12,66,4.488636,0,2.302395,0.0,0.0,0.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [3]:
X = train_df.drop('log_count', axis=1)
y = train_df['log_count']

In [4]:
display(X)
display(y)

,temp,humidity,year,log_windspeed,season_1,season_2,season_3,season_4,weather_1,weather_3,...,hour_14,hour_15,hour_16,hour_17,hour_18,hour_19,hour_20,hour_21,hour_22,hour_23
0,9.84,81,1,0.000000,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,9.02,80,1,0.000000,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,9.02,80,1,0.000000,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,9.84,75,1,0.000000,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,9.84,75,1,0.000000,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10881,15.58,50,0,3.295937,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
10882,14.76,57,0,2.772670,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
10883,13.94,61,0,2.772670,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
10884,13.94,61,0,1.946367,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
10885,13.12,66,0,2.302395,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

0        2.833213
1        3.713572
2        3.496508
3        2.639057
4        0.693147
           ...
10881    5.820083
10882    5.488938
10883    5.129899
10884    4.867534
10885    4.488636
Name: log_count, Length: 10886, dtype: float64

In [5]:
scaler1 = StandardScaler()
X_scaled = scaler1.fit_transform(X)
X_scaled

array([[-1.33366069,  0.99321305,  1.00386564, ..., -0.20909337,
        -0.20909337, -0.20909337],
       [-1.43890721,  0.94124921,  1.00386564, ..., -0.20909337,
        -0.20909337, -0.20909337],
       [-1.43890721,  0.94124921,  1.00386564, ..., -0.20909337,
        -0.20909337, -0.20909337],
       ...,
       [-0.80742813, -0.04606385, -0.99614925, ...,  4.78255235,
        -0.20909337, -0.20909337],
       [-0.80742813, -0.04606385, -0.99614925, ..., -0.20909337,
         4.78255235, -0.20909337],
       [-0.91267464,  0.21375537, -0.99614925, ..., -0.20909337,
        -0.20909337,  4.78255235]], shape=(10886, 43))

### KNeighborsRegressor 하이퍼 파라미터 튜닝

In [6]:
def objective(trial) :
    params = {
        # 이웃의 개수
        # 회귀에서는 이웃들의 평균(또는 가중 평균)을 구한다.
        'n_neighbors' : trial.suggest_int('n_neighbors', 1, 100),
        # 가중치 결정 방식
        # uniform : 모두에게 동일한 가중치를 부여
        # distance : 거리가 가까운 데이터의 가중치를 더 부여
        'weights' : trial.suggest_categorical('weights', ['uniform', 'distance']),
        # 거리 측정방식
        'metric' : trial.suggest_categorical('metric', ['euclidean', 'manhattan', 'minkowski', 'chebyshev']),
        # 이웃 탐색 알고리즘
        'algorithm' : trial.suggest_categorical('algorithm', ['auto', 'ball_tree', 'kd_tree', 'brute']),
        # 트리의 최소 노드 크기
        'leaf_size' : trial.suggest_int('leaf_size', 10, 60),
        # 병렬 처리
        'n_jobs' : -1
    }

    # 거리측정방식이 minkowski 라면
    if params['metric'] == 'minkowski' :
        params['p'] = trial.suggest_float('p', 1.0, 5.0)

    # 모델 생성
    model = KNeighborsRegressor(**params)
    kf = KFold(n_splits=5, shuffle=True, random_state=42)
    score = cross_val_score(model, X_scaled, y, cv=kf, scoring='r2').mean()
    return score

sampler = TPESampler(seed=42)
study = optuna.create_study(direction='maximize', sampler=sampler, pruner=MedianPruner(n_warmup_steps=10))
study.optimize(objective, n_trials=50, show_progress_bar=True)

knn_params = study.best_params.copy()
knn_score = study.best_value

print(f'최적 파라미터 : {knn_params}')
print(f'최고 R2 점수 : {knn_score}')

  0%|          | 0/50 [00:00<?, ?it/s]

최적 파라미터 : {'n_neighbors': 46, 'weights': 'distance', 'metric': 'manhattan', 'algorithm': 'ball_tree', 'leaf_size': 46}
최고 R2 점수 : 0.8110910210099137

### LinearRegression 하이퍼 파라미터 튜닝

In [7]:
def objective(trial) :
    params = {
        # 모형에 상수항을 계산할지 여부
        # 데이터가 이미 원점을 지나도록 전처리되었다면 False로 설정하기도 함.
        'fit_intercept' : trial.suggest_categorical('fit_intercept', [True, False]),
        # 학습 시 입력 데이터를 복하해서 사용할지 여부
        # False일 경우 원본 데이터가 변경될 수 있지만 메모리를 절약한다.
        'copy_X' : trial.suggest_categorical('copy_X', [True, False]),
        # 회귀 계수(기울기)를 무조건 양수로 제한할지 여부
        # 특정 도메인에서 음수 계수가 나오면 안 될 때 사용한다.
        'positive' : trial.suggest_categorical('positive', [True, False]),
        # 모든 CPU 코어를 사용하겠다
        'n_jobs' : -1
    }

    model = LinearRegression(**params)
    kf = KFold(n_splits=5, shuffle=True, random_state=42)
    score = cross_val_score(model, X_scaled, y, cv=kf, scoring='r2').mean()
    return score

sampler = TPESampler(seed=42)
study = optuna.create_study(direction='maximize', sampler=sampler, pruner=MedianPruner(n_warmup_steps=10))
study.optimize(objective, n_trials=50, show_progress_bar=True)

lr_params = study.best_params.copy()
lr_score = study.best_value

print(f'최적 파라미터 : {lr_params}')
print(f'최고 R2 점수 : {lr_score}')

  0%|          | 0/50 [00:00<?, ?it/s]

최적 파라미터 : {'fit_intercept': True, 'copy_X': False, 'positive': False}
최고 R2 점수 : 0.8291325676996888

### Ridge 하이퍼 파라미터 튜닝

In [8]:
def objective(trial) :
    params = {
        # 규제의 강도를 결정하는 핵심 파라미터
        # 값이 클수록 규제가 강해져 계수가 0에 가까워진다(모델이 단순해진다)
        'alpha' : trial.suggest_float('alpha', 1e-3, 100.0, log=True),
        # 절편(혹은 바이어스)를 계산할지 여부
        'fit_intercept' : trial.suggest_categorical('fit_intercept', [True, False]),
        # 계산에 사용할 알고리즘
        # auto : 데이터에 따라 자동 선택
        # svd : 특이값 분해 (데이터가 클 때 유리)
        # cholesky : 표준적인 계산 방식
        # sag / saga : 확률적 평균 경사 하강법 (대용량 데이터에 최적)
        'solver' : trial.suggest_categorical('solver', ['auto', 'svd', 'cholesky', 'sag', 'saga']),
        # 반복 횟수 (solver가 sag, saga일 경우 사용)
        'max_iter' : 1000,
        # 랜덤 시드
        'random_state' : 42
    }

    model = Ridge(**params)
    kf = KFold(n_splits=5, shuffle=True, random_state=42)
    score = cross_val_score(model, X_scaled, y, cv=kf, scoring='r2').mean()
    return score

sampler = TPESampler(seed=42)
study = optuna.create_study(direction='maximize', sampler=sampler, pruner=MedianPruner(n_warmup_steps=10))
study.optimize(objective, n_trials=50, show_progress_bar=True)

ridge_params = study.best_params.copy()
ridge_score = study.best_value

print(f'최적 파라미터 : {ridge_params}')
print(f'최적 R2 점수 : {ridge_score}')

  0%|          | 0/50 [00:00<?, ?it/s]

최적 파라미터 : {'alpha': 12.601010727086686, 'fit_intercept': True, 'solver': 'saga'}
최적 R2 점수 : 0.8293762246481837

### Lasso 하이퍼 파라미터 튜닝

In [9]:
def objective(trial) :
    params = {
        # L1 규제 강도
        # 0에 가까우면 일반 선형 회귀, 커질 수록 더 많은 변수의 계수가 0이 된다.
        'alpha' : trial.suggest_float('alpha', 1e-4, 10.0, log=True),
        # fit_intercept : 절편 계산 여부
        'fit_intercept' : trial.suggest_categorical('fit_intercept', [True, False]),
        # 계수를 업데이트하는 방식
        # cyclic : 변수 순서대로 업데이트
        # random : 무작위 업데이트 (빠르게 끝날 수도 있지만 최적의 가중치를 찾지 못할 수도 있다)
        'selection' : trial.suggest_categorical('selection', ['cyclic', 'random']),
        # 최대 반복 횟수
        # Lasso는 오랫동안 학습해야 하는 경우가 많기 때문에 많이 주세요
        'max_iter' : 2000,
        # 랜덤시드
        'random_state' : 42
    }

    model = Lasso(**params)
    kf = KFold(n_splits=5, shuffle=True, random_state=42)
    score = cross_val_score(model, X_scaled, y, cv=kf, scoring='r2').mean()
    return score

sampler = TPESampler(seed=42)
study = optuna.create_study(direction='maximize', sampler=sampler, pruner=MedianPruner(n_warmup_steps=10))
study.optimize(objective, n_trials=50, show_progress_bar=True)

lasso_params = study.best_params.copy()
lasso_score = study.best_value

print(f'최적 파라미터 : {lasso_params}')
print(f'최고 R2 점수 : {lasso_score}')

  0%|          | 0/50 [00:00<?, ?it/s]

최적 파라미터 : {'alpha': 0.0001128445313593244, 'fit_intercept': True, 'selection': 'random'}
최고 R2 점수 : 0.8293752145637404

### ElasticNet 하이퍼 파라미터 튜닝

In [10]:
def objective(trial) :
    params = {
        # 규제 강도 : L1 + L2 합산 강도
        'alpha' : trial.suggest_float('alpha', 1e-4, 10.0, log=True),
        # 규제 비율
        # 0에 가까우면 Ridge와 비슷, 1에 가까우면 Lasso와 비슷
        # 0.5면 L1과 L2를 반반씩 섞은 형태이다
        'l1_ratio' : trial.suggest_float('l1_ratio', 0.0, 1.0),
        # 절편 계산 여부
        'fit_intercept' : trial.suggest_categorical('fit_intercept', [True, False]),
        # 반복횟수
        'max_iter' : 2000,
        # 랜덤 시드
        'random_state' : 42
    }

    model = ElasticNet(**params)
    kf = KFold(n_splits=5, shuffle=True, random_state=42)
    score = cross_val_score(model, X_scaled, y, cv=kf, scoring='r2').mean()
    return score

sampler = TPESampler(seed=42)
study = optuna.create_study(direction='maximize', sampler=sampler, pruner=MedianPruner(n_warmup_steps=10))
study.optimize(objective, n_trials=50, show_progress_bar=True)

en_params = study.best_params.copy()
en_score = study.best_value

print(f'최적 파라미터 : {en_params}')
print(f'최고 R2 점수 : {en_score}')

  0%|          | 0/50 [00:00<?, ?it/s]

최적 파라미터 : {'alpha': 0.0009162724884836632, 'l1_ratio': 0.566218510535344, 'fit_intercept': True}
최고 R2 점수 : 0.8293775549520621

### SVR 하이퍼 파라미터 튜닝

In [11]:
def objective(trial) :
    params = {
        # 데이터의 비 선형성을 처리하는 방식
        'kernel' : trial.suggest_categorical('kernel', ['linear', 'poly', 'rbf', 'sigmoid']),
        # 규제 강도의 역수
        # 크면 오차를 적게 허용(과적합 위험), 작으면 부드러운 경계(과소적합 위험)
        'C' : trial.suggest_float('C', 1e-3, 100.0, log=True),
        # 튜브의 너비
        # 이 범위내의 오차는 손실로 계산하지 않는다.
        'epsilon' : trial.suggest_float('epsilon', 0.01, 1.0, log=True),
        # 커널의 영향력의 범위 (rbf, poly, sigmoid에서 중요)
        # 'scale'은 피처의 수에 반비례, auto의 피처 수의 역수
        'gamma' : trial.suggest_categorical('gamma', ['scale', 'auto']),
        # poly 커널 사용시 다항식의 차수
        'degree' : trial.suggest_int('degree', 2, 5) if trial.params.get('kernel') == 'poly' else 3,
        # 계산을 위한 메모리 할당 (MB 단위)
        'cache_size' : 1000
    }

    model = SVR(**params)
    kf = KFold(n_splits=5, shuffle=True, random_state=42)
    score = cross_val_score(model, X_scaled, y, cv=kf, scoring='r2').mean()
    return score

sampler = TPESampler(seed=42)
study = optuna.create_study(direction='maximize', sampler=sampler, pruner=MedianPruner(n_warmup_steps=10))
study.optimize(objective, n_trials=50, show_progress_bar=True)

svr_params = study.best_params.copy()
svr_score = study.best_value

print(f'최적 파라미터 : {svr_params}')
print(f'최고 R2 점수 : {svr_score}')

  0%|          | 0/50 [00:00<?, ?it/s]

최적 파라미터 : {'kernel': 'linear', 'C': 2.820926771119946, 'epsilon': 0.5333740234646415, 'gamma': 'scale'}
최고 R2 점수 : 0.8262362258078356

### DesionTreeRegressor 하이퍼 파라미터 튜닝

In [12]:
def objective(trial) :
    params = {
        # 분할의 품질을 측정하는 함수
        # squared_error : 평균 제곱 오차
        # absolute_error : 평균 절대 오차
        # friedman_mse : mse를 조금 개선한 방식
        'criterion' : trial.suggest_categorical('criterion', ['squared_error', 'friedman_mse', 'absolute_error']),
        # 트리의 최대 깊이
        # 너무 깊으면 과적합, 너무 낮으면 과소적합 발생
        'max_depth' : trial.suggest_int('max_depth', 3, 20),
        # 노드를 분할하기 위해 필요한 최소 샘플 수
        'min_samples_split' : trial.suggest_int('min_samples_split', 2, 20),
        # 리프 노드(말단 노드)가 되기 위해 필요한 최소 샘플 수
        'min_samples_leaf' : trial.suggest_int('min_samples_leaf', 1, 20),
        # 최적의 분할을 찾기 위해 고려할 피처의 개수
        'max_features' : trial.suggest_categorical('max_features', [None, 'sqrt', 'log2']),
        # 랜덤 시드
        'random_state' : 42
    }

    model = DecisionTreeRegressor(**params)
    kf = KFold(n_splits=5, shuffle=True, random_state=42)
    score = cross_val_score(model, X_scaled, y, cv=kf, scoring='r2').mean()
    return score

sampler = TPESampler(seed=42)
study = optuna.create_study(direction='maximize', sampler=sampler, pruner=MedianPruner(n_warmup_steps=10))
study.optimize(objective, n_trials=50, show_progress_bar=True)

dt_params = study.best_params.copy()
dt_score = study.best_value

print(f'최적 파라미터 : {dt_params}')
print(f'최고 R2 점수 : {dt_score}')

  0%|          | 0/50 [00:00<?, ?it/s]

최적 파라미터 : {'criterion': 'friedman_mse', 'max_depth': 20, 'min_samples_split': 12, 'min_samples_leaf': 15, 'max_features': None}
최고 R2 점수 : 0.8053317612878743

### RandomForestRegressor 하이퍼 파라미터 튜닝

In [13]:
def objective(trial) :
    params = {
        # 트리의 개수
        # 너무 적으면 성능이 낮고, 너무 많으면 계산 시간이 오래 걸린다.
        'n_estimators' : trial.suggest_int('n_estimators', 100, 500),
        # 각 트리의 최대 깊이
        'max_depth' : trial.suggest_int('max_depth', 3, 20),
        # 노드 분할을 위한 최소 샘플 수
        'min_samples_split' : trial.suggest_int('min_samples_split', 2, 20),
        # 리프 노드에 필요한 최소 샘플 수
        'min_samples_leaf' : trial.suggest_int('min_samples_leaf', 1, 20),
        # 최적의 분할을 찾기 위해 고려할 피처의 개수
        'max_features' : trial.suggest_categorical('max_features', [None, 'sqrt', 'log2']),
        # 중복을 허용한 샘플링 사용 여부
        'bootstrap' : trial.suggest_categorical('bootstrap', [True, False]),
        # 모든 CPU 사용
        'n_jobs' : -1,
        # 랜덤 시드
        'random_state' : 42
    }

    model = RandomForestRegressor(**params)
    kf = KFold(n_splits=5, shuffle=True, random_state=42)
    score = cross_val_score(model, X_scaled, y, cv=kf, scoring='r2').mean()
    return score

sampler = TPESampler(seed=42)
study = optuna.create_study(direction='maximize', sampler=sampler, pruner=MedianPruner(n_warmup_steps=10))
study.optimize(objective, n_trials=50, show_progress_bar=True)

rf_params = study.best_params.copy()
rf_score = study.best_value

print(f'최적 파라미터 : {rf_params}')
print(f'최고 R2 점수 : {rf_score}')

  0%|          | 0/50 [00:00<?, ?it/s]

최적 파라미터 : {'n_estimators': 359, 'max_depth': 20, 'min_samples_split': 7, 'min_samples_leaf': 6, 'max_features': None, 'bootstrap': True}
최고 R2 점수 : 0.8298293806581636

### GradientBoostRegressor 하이퍼 파라미터 튜닝

In [14]:
def objective(trial) :
    params = {
        # 트리의 개수
        # 너무 많으면 과적합, 너무 적으면 학습 부족
        'n_estimators' : trial.suggest_int('n_estimators', 100, 500),
        # 학습률
        # 적으면 정교하지만 많은 트리가 필요함
        'learning_rate' : trial.suggest_float('learning_rate', 0.001, 0.2, log=True),
        # 개별 트리의 최대 깊이
        # 부스팅에서는 깊지 않은 트리를 많이 두는 것이 효과적이다.
        'max_depth' : trial.suggest_int('max_depth', 3, 10),
        # 노드 분할을 위한 최소 샘플 수
        'min_samples_split' : trial.suggest_int('min_samples_split', 2, 20),
        # 리프 노드에 필요한 최소 샘플 수
        'min_samples_leaf' : trial.suggest_int('min_samples_leaf', 1, 20),
        # 각 트리학습에 사용할 데이터 비율
        'subsample' : trial.suggest_float('subsample', 0.5, 1.0),
        # 최적 분할을 위해 사용할 피처의 비율
        'max_features' : trial.suggest_categorical('max_features', ['sqrt', 'log2', None]),
        # 랜덤 시드
        'random_state' : 42
    }

    model = GradientBoostingRegressor(**params)
    kf = KFold(n_splits=5, shuffle=True, random_state=42)
    score = cross_val_score(model, X_scaled, y, cv=kf, scoring='r2').mean()
    return score

sampler = TPESampler(seed=42)
study = optuna.create_study(direction='maximize', sampler=sampler, pruner=MedianPruner(n_warmup_steps=10))
study.optimize(objective, n_trials=50, show_progress_bar=True)

gb_params = study.best_params.copy()
gb_score = study.best_value

print(f'최적 파라미터 : {gb_params}')
print(f'최고 R2 점수 : {gb_score}')

  0%|          | 0/50 [00:00<?, ?it/s]

최적 파라미터 : {'n_estimators': 148, 'learning_rate': 0.06927499365137466, 'max_depth': 7, 'min_samples_split': 16, 'min_samples_leaf': 19, 'subsample': 0.5809488368401539, 'max_features': None}
최고 R2 점수 : 0.8388560177529361

### LGBMRegressor 하이퍼 파라미터 튜닝

In [15]:
def objective(trial) :
    params = {
        # 트리의 개수
        'n_estimators' : trial.suggest_int('n_estimators', 100, 1000),
        # 학습률
        'learning_rate' : trial.suggest_float('learning_rate', 0.005, 0.2, log=True),
        # 트리의 최대 깊이
        'max_depth' : trial.suggest_int('max_depth', 3, 15),
        # 하나의 트리가 가질 수 있는 최대 리프 수 (LGBM의 핵심 파라미터)
        'num_leaves' : trial.suggest_int('num_leaves', 2, 256),
        # 리프 노드가 되기 위한 최소 데이터 수 (과적합 제어)
        'min_child_samples' : trial.suggest_int('min_child_samples', 5, 100),
        # 데이터 샘플링 비율
        'subsample' : trial.suggest_float('subsample', 0.5, 1.0),
        # 개별 트리 학습 시 무작위로 선택되는 피처 비율
        'colsample_bytree' : trial.suggest_float('colsample_bytree', 0.5, 1.0),
        # L1 규제 강도
        'reg_alpha' : trial.suggest_float('reg_alpha', 1e-8, 10.0, log=True),
        # L2 규제 강도
        'reg_lambda' : trial.suggest_float('reg_lambda', 1e-8, 1.0, log=True),
        # cpu 코어 최대 활용
        'n_jobs' : -1,
        # 랜덤시트
        'random_state' : 42,
        # 로그 출력 안하게..
        'verbosity' : -1
    }

    model = LGBMRegressor(**params)
    kf = KFold(n_splits=5, shuffle=True, random_state=42)
    score = cross_val_score(model, X_scaled, y, cv=kf, scoring='r2').mean()
    return score

sampler = TPESampler(seed=42)
study = optuna.create_study(direction='maximize', sampler=sampler, pruner=MedianPruner(n_warmup_steps=10))
study.optimize(objective, n_trials=50, show_progress_bar=True)

lgbm_params = study.best_params.copy()
lgbm_score = study.best_value

print(f'최적 파라미터 : {lgbm_params}')
print(f'최고 R2 점수 : {lgbm_score}')

  0%|          | 0/50 [00:00<?, ?it/s]

최적 파라미터 : {'n_estimators': 275, 'learning_rate': 0.062482541175872326, 'max_depth': 9, 'num_leaves': 90, 'min_child_samples': 45, 'subsample': 0.9319818188945931, 'colsample_bytree': 0.7778972539293485, 'reg_alpha': 0.029514153215150038, 'reg_lambda': 0.009023643309113781}
최고 R2 점수 : 0.8402474291914865

### XGBoost Regressor 하이퍼 파라미터 튜닝

In [17]:
def objective(trial) :
    params = {
        # GPU 사용 설정
        'device' : 'cuda',
        'tree_method' : 'hist',
        # 트리의 개수
        'n_estimators' : trial.suggest_int('n_estimators', 100, 1000),
        # 학습률
        'learning_rate' : trial.suggest_float('learning_rate', 0.005, 0.2, log=True),
        # 트르의 최대 깊이
        'max_depth' : trial.suggest_int('max_depth', 3, 10),
        # 가중치 합의 최소치 (과적합 제어)
        'min_child_weight' : trial.suggest_int('min_child_weight', 1, 10),
        # 데이터 샘플링 비율
        'subsample' : trial.suggest_float('subsample', 0.5, 1.0),
        # 트리 생성시 사용할 피처 비율
        'colsample_bytree' : trial.suggest_float('colsample_bytree', 0.5, 1.0),
        # 노드 분할을 위한 최소 손실 감소 값
        'gamma' : trial.suggest_float('gamma', 1e-8, 1.0, log=True),
        # L1 규제 강도
        'reg_alpha' : trial.suggest_float('reg_alpha', 1e-8, 10.0, log=True),
        # L2 규제 강도
        'reg_lambda' : trial.suggest_float('reg_lambda', 1e-8, 10.0, log=True),
        # 랜덤시드
        'random_state' : 42,
        'verbosity' : 0,
    }

    model = XGBRegressor(**params)
    kf = KFold(n_splits=5, shuffle=True, random_state=42)
    score = cross_val_score(model, X_scaled, y, cv=kf, scoring='r2').mean()
    return score

sampler = TPESampler(seed=42)
study = optuna.create_study(direction='maximize', sampler=sampler, pruner=MedianPruner(n_warmup_steps=10))
study.optimize(objective, n_trials=50, show_progress_bar=True)

xgb_params = study.best_params.copy()
xgb_score = study.best_value

print(f'최적 파라미터 : {xgb_params}')
print(f'최고 R2 점수 : {xgb_score}')

  0%|          | 0/50 [00:00<?, ?it/s]

최적 파라미터 : {'n_estimators': 790, 'learning_rate': 0.07290966282108481, 'max_depth': 6, 'min_child_weight': 6, 'subsample': 0.6642080088862329, 'colsample_bytree': 0.9012259236600972, 'gamma': 0.030593368645669947, 'reg_alpha': 8.799979362325798, 'reg_lambda': 6.193434549890812}
최고 R2 점수 : 0.838471102327085

### BayesianRidge 하이퍼 파라미터 튜닝

In [20]:
def objective(trial) :
    params = {
        # 최복 반복 횟수
        'max_iter' : trial.suggest_int('max_iter', 100, 1000),
        # 허용 오차
        'tol' : trial.suggest_float('tol', 1e-6, 1e-2, log=True),
        # 감마 분포 파라미터 (정규화 관련)
        'alpha_1' : trial.suggest_float('alpha_1', 1e-8, 1e-2, log=True),
        'alpha_2' : trial.suggest_float('alpha_2', 1e-8, 1e-2, log=True),
        # 가중치 정밀도에 대한 파라미터
        'lambda_1' : trial.suggest_float('lambda_1', 1e-8, 1e-2, log=True),
        'lambda_2' : trial.suggest_float('lambda_2', 1e-8, 1e-2, log=True),
        # 절편 계산 여부
        'fit_intercept' : trial.suggest_categorical('fit_intercept', [True, False])
    }

    model = BayesianRidge(**params)
    kf = KFold(n_splits=5, shuffle=True, random_state=42)
    score = cross_val_score(model, X_scaled, y, cv=kf, scoring='r2').mean()
    return score

sampler = TPESampler(seed=42)
study = optuna.create_study(direction='maximize', sampler=sampler, pruner=MedianPruner(n_warmup_steps=10))
study.optimize(objective, n_trials=50, show_progress_bar=True)

br_params = study.best_params.copy()
br_score = study.best_value

print(f'최적 파라미터 : {br_params}')
print(f'최고 R2 점수 : {br_score}')

  0%|          | 0/50 [00:00<?, ?it/s]

최적 파라미터 : {'max_iter': 819, 'tol': 9.534392667816801e-05, 'alpha_1': 1.49310808660669e-06, 'alpha_2': 2.0492023060949682e-07, 'lambda_1': 0.009965544658508204, 'lambda_2': 1.9044737441968943e-06, 'fit_intercept': True}
최고 R2 점수 : 0.8293749850761113

### CatBoost Regressor 하이퍼 파라미터 튜닝

In [24]:
def objective(trial) :
    params = {
        # gpu 설정
        'task_type' : 'GPU',
        'devices' : '0',
        # 트리의 개수
        'iterations' : trial.suggest_int('iterations', 100, 1000),
        # 학습률
        'learning_rate' : trial.suggest_float('learning_rate', 0.005, 0.2, log=True),
        # 트리의 깊이
        'depth' : trial.suggest_int('depth', 4, 10),
        # L2 규제 강도
        'l2_leaf_reg' : trial.suggest_float('l2_leaf_reg', 1e-2, 10.0, log=True),
        # 분할 선택시 무작위성 강도 (과적합 방지)
        'random_strength' : trial.suggest_float('random_strength', 1e-8, 10.0, log=True),
        # 배깅 강도(0이면 배깅 없음, 높을 수록 무작위성 증가)
        'bagging_temperature' : trial.suggest_float('bagging_temperature', 0.0, 1.0),
        # 수치형 피처를 나는 최소 단위 (GPU 사용시 중요)
        'border_count' : trial.suggest_int('border_count', 32, 255),
        # 랜덤 시드
        'random_state' : 42,
        # 로그 출력 안되게..
        'verbose' : False,
        'allow_writing_files' : False
    }

    model = CatBoostRegressor(**params)
    kf = KFold(n_splits=5, shuffle=True, random_state=42)
    score = cross_val_score(model, X_scaled, y, cv=kf, scoring='r2').mean()
    return score

sampler = TPESampler(seed=42)
study = optuna.create_study(direction='maximize', sampler=sampler, pruner=MedianPruner(n_warmup_steps=10))
study.optimize(objective, n_trials=50, show_progress_bar=True)

cat_params = study.best_params.copy()
cat_score = study.best_value

print(f'최적 파라미터 : {cat_params}')
print(f'최고 R2 점수 : {cat_score}')

  0%|          | 0/50 [00:00<?, ?it/s]

최적 파라미터 : {'iterations': 914, 'learning_rate': 0.09071323097849458, 'depth': 10, 'l2_leaf_reg': 0.010372443311347384, 'random_strength': 3.5357575714365087e-06, 'bagging_temperature': 0.863088365265509, 'border_count': 64}
최고 R2 점수 : 0.8422217766728034

### 종합 정리

In [26]:
score_list = [
    knn_score, lr_score, ridge_score, lasso_score, en_score, svr_score, dt_score,
    rf_score, gb_score, lgbm_score, xgb_score, br_score, cat_score
]

model_names = [
    'KNeighborsRegressor', 'LinearRegression', 'Ridge', 'Lasso', 'ElasticNet',
    'SVR', 'DecisionTreeRegressor', 'RandomForestRegressor', 'GradientBoostingRegressor',
    'LGBMRegressor', 'XGBRegressor', 'BayesianRidge', 'CatBoostRegressor'
]

score_df = pd.DataFrame(score_list, index=model_names, columns=['score'])
score_df.sort_values('score', ascending=False, inplace=True)
score_df

                              score
CatBoostRegressor          0.842222
LGBMRegressor              0.840247
GradientBoostingRegressor  0.838856
XGBRegressor               0.838471
RandomForestRegressor      0.829829
ElasticNet                 0.829378
Ridge                      0.829376
Lasso                      0.829375
BayesianRidge              0.829375
LinearRegression           0.829133
SVR                        0.826236
KNeighborsRegressor        0.811091
DecisionTreeRegressor      0.805332

In [27]:
best_model = CatBoostRegressor(**cat_params)
best_model.fit(X_scaled, y)

0:	learn: 1.3229420	total: 11.5ms	remaining: 10.5s
1:	learn: 1.2375740	total: 16.8ms	remaining: 7.65s
2:	learn: 1.1608710	total: 20.7ms	remaining: 6.29s
3:	learn: 1.0933735	total: 24.8ms	remaining: 5.64s
4:	learn: 1.0338533	total: 28.8ms	remaining: 5.24s
5:	learn: 0.9803775	total: 33.4ms	remaining: 5.06s
6:	learn: 0.9341827	total: 37.9ms	remaining: 4.91s
7:	learn: 0.8930450	total: 42.2ms	remaining: 4.78s
8:	learn: 0.8570277	total: 46.3ms	remaining: 4.65s
9:	learn: 0.8248652	total: 52ms	remaining: 4.7s
10:	learn: 0.7965648	total: 58.6ms	remaining: 4.81s
11:	learn: 0.7718618	total: 62.9ms	remaining: 4.73s
12:	learn: 0.7502772	total: 67.2ms	remaining: 4.66s
13:	learn: 0.7311327	total: 71.1ms	remaining: 4.57s
14:	learn: 0.7136709	total: 74.8ms	remaining: 4.49s
15:	learn: 0.6979460	total: 78.8ms	remaining: 4.42s
16:	learn: 0.6838765	total: 82.9ms	remaining: 4.37s
17:	learn: 0.6717249	total: 86.7ms	remaining: 4.31s
18:	learn: 0.6599537	total: 90.3ms	remaining: 4.25s
19:	learn: 0.6498066	total: 93.9ms	remaining: 4.2s
20:	learn: 0.6408391	total: 97.8ms	remaining: 4.16s
21:	learn: 0.6325508	total: 102ms	remaining: 4.12s
22:	learn: 0.6247867	total: 105ms	remaining: 4.08s
23:	learn: 0.6179129	total: 109ms	remaining: 4.05s
24:	learn: 0.6122929	total: 113ms	remaining: 4.03s
25:	learn: 0.6067859	total: 117ms	remaining: 4.01s
26:	learn: 0.6019207	total: 121ms	remaining: 3.99s
27:	learn: 0.5963027	total: 125ms	remaining: 3.96s
28:	learn: 0.5918701	total: 129ms	remaining: 3.93s
29:	learn: 0.5882149	total: 133ms	remaining: 3.91s
30:	learn: 0.5843079	total: 137ms	remaining: 3.89s
31:	learn: 0.5812725	total: 140ms	remaining: 3.87s
32:	learn: 0.5770158	total: 145ms	remaining: 3.86s
33:	learn: 0.5739459	total: 149ms	remaining: 3.85s
34:	learn: 0.5703556	total: 153ms	remaining: 3.83s
35:	learn: 0.5678831	total: 157ms	remaining: 3.82s
36:	learn: 0.5656231	total: 160ms	remaining: 3.8s
37:	learn: 0.5620354	total: 164ms	remaining: 3.78s
38:	learn: 0.5601062	total: 168ms	remaining: 3.77s
39:	learn: 0.5580248	total: 172ms	remaining: 3.76s
40:	learn: 0.5556206	total: 176ms	remaining: 3.76s
41:	learn: 0.5539572	total: 181ms	remaining: 3.75s
42:	learn: 0.5523157	total: 184ms	remaining: 3.74s
43:	learn: 0.5510788	total: 188ms	remaining: 3.72s
44:	learn: 0.5486605	total: 192ms	remaining: 3.71s
45:	learn: 0.5474467	total: 196ms	remaining: 3.7s
46:	learn: 0.5452758	total: 200ms	remaining: 3.69s
47:	learn: 0.5430178	total: 204ms	remaining: 3.68s
48:	learn: 0.5402547	total: 208ms	remaining: 3.68s
49:	learn: 0.5394281	total: 213ms	remaining: 3.68s
50:	learn: 0.5380560	total: 217ms	remaining: 3.67s
51:	learn: 0.5358811	total: 221ms	remaining: 3.66s
52:	learn: 0.5336399	total: 225ms	remaining: 3.66s
53:	learn: 0.5324348	total: 229ms	remaining: 3.65s
54:	learn: 0.5295947	total: 233ms	remaining: 3.64s
55:	learn: 0.5272327	total: 237ms	remaining: 3.63s
56:	learn: 0.5255314	total: 241ms	remaining: 3.63s
57:	learn: 0.5248064	total: 245ms	remaining: 3.62s
58:	learn: 0.5227150	total: 249ms	remaining: 3.61s
59:	learn: 0.5218105	total: 253ms	remaining: 3.6s
60:	learn: 0.5206304	total: 257ms	remaining: 3.59s
61:	learn: 0.5185139	total: 261ms	remaining: 3.58s
62:	learn: 0.5174085	total: 265ms	remaining: 3.57s
63:	learn: 0.5153486	total: 268ms	remaining: 3.56s
64:	learn: 0.5144515	total: 273ms	remaining: 3.56s
65:	learn: 0.5132840	total: 277ms	remaining: 3.56s
66:	learn: 0.5113800	total: 282ms	remaining: 3.56s
67:	learn: 0.5101191	total: 286ms	remaining: 3.55s
68:	learn: 0.5093511	total: 290ms	remaining: 3.55s
69:	learn: 0.5082549	total: 294ms	remaining: 3.55s
70:	learn: 0.5063635	total: 299ms	remaining: 3.55s
71:	learn: 0.5048042	total: 303ms	remaining: 3.54s
72:	learn: 0.5029738	total: 307ms	remaining: 3.53s
73:	learn: 0.5013249	total: 311ms	remaining: 3.53s
74:	learn: 0.4997766	total: 315ms	remaining: 3.52s
75:	learn: 0.4989947	total: 319ms	remaining: 3.52s
76:	learn: 0.4982074	total: 323ms	remaining: 3.51s
77:	learn: 0.4972740	total: 327ms	remaining: 3.51s
78:	learn: 0.4959608	total: 331ms	remaining: 3.5s
79:	learn: 0.4947858	total: 335ms	remaining: 3.49s
80:	learn: 0.4937085	total: 339ms	remaining: 3.48s
81:	learn: 0.4926465	total: 343ms	remaining: 3.48s
82:	learn: 0.4922272	total: 347ms	remaining: 3.47s
83:	learn: 0.4916075	total: 350ms	remaining: 3.46s
84:	learn: 0.4902854	total: 354ms	remaining: 3.45s
85:	learn: 0.4888869	total: 358ms	remaining: 3.45s
86:	learn: 0.4882949	total: 362ms	remaining: 3.44s
87:	learn: 0.4878991	total: 366ms	remaining: 3.44s
88:	learn: 0.4867505	total: 370ms	remaining: 3.43s
89:	learn: 0.4854798	total: 374ms	remaining: 3.42s
90:	learn: 0.4847599	total: 377ms	remaining: 3.41s
91:	learn: 0.4832951	total: 381ms	remaining: 3.4s
92:	learn: 0.4823881	total: 385ms	remaining: 3.39s
93:	learn: 0.4815770	total: 388ms	remaining: 3.39s
94:	learn: 0.4798472	total: 392ms	remaining: 3.38s
95:	learn: 0.4787120	total: 396ms	remaining: 3.38s
96:	learn: 0.4769108	total: 400ms	remaining: 3.37s
97:	learn: 0.4754939	total: 404ms	remaining: 3.36s
98:	learn: 0.4747410	total: 408ms	remaining: 3.36s
99:	learn: 0.4737068	total: 412ms	remaining: 3.35s
100:	learn: 0.4723388	total: 415ms	remaining: 3.34s
101:	learn: 0.4716076	total: 419ms	remaining: 3.34s
102:	learn: 0.4709785	total: 423ms	remaining: 3.33s
103:	learn: 0.4696434	total: 426ms	remaining: 3.32s
104:	learn: 0.4689565	total: 430ms	remaining: 3.31s
105:	learn: 0.4682041	total: 434ms	remaining: 3.31s
106:	learn: 0.4671638	total: 438ms	remaining: 3.31s
107:	learn: 0.4661849	total: 442ms	remaining: 3.3s
108:	learn: 0.4651773	total: 446ms	remaining: 3.29s
109:	learn: 0.4641640	total: 449ms	remaining: 3.28s
110:	learn: 0.4633599	total: 453ms	remaining: 3.27s
111:	learn: 0.4623328	total: 456ms	remaining: 3.27s
112:	learn: 0.4613302	total: 460ms	remaining: 3.26s
113:	learn: 0.4604964	total: 464ms	remaining: 3.25s
114:	learn: 0.4602725	total: 467ms	remaining: 3.25s
115:	learn: 0.4595769	total: 471ms	remaining: 3.24s
116:	learn: 0.4584875	total: 475ms	remaining: 3.23s
117:	learn: 0.4578482	total: 479ms	remaining: 3.23s
118:	learn: 0.4567458	total: 482ms	remaining: 3.22s
119:	learn: 0.4558802	total: 486ms	remaining: 3.21s
120:	learn: 0.4545671	total: 489ms	remaining: 3.21s
121:	learn: 0.4534712	total: 493ms	remaining: 3.2s
122:	learn: 0.4522561	total: 497ms	remaining: 3.19s
123:	learn: 0.4512006	total: 501ms	remaining: 3.19s
124:	learn: 0.4498178	total: 505ms	remaining: 3.18s
125:	learn: 0.4486146	total: 508ms	remaining: 3.18s
126:	learn: 0.4476523	total: 512ms	remaining: 3.17s
127:	learn: 0.4467086	total: 516ms	remaining: 3.17s
128:	learn: 0.4460113	total: 519ms	remaining: 3.16s
129:	learn: 0.4450449	total: 523ms	remaining: 3.15s
130:	learn: 0.4442545	total: 526ms	remaining: 3.15s
131:	learn: 0.4432557	total: 530ms	remaining: 3.14s
132:	learn: 0.4423724	total: 534ms	remaining: 3.13s
133:	learn: 0.4411728	total: 537ms	remaining: 3.13s
134:	learn: 0.4403012	total: 541ms	remaining: 3.12s
135:	learn: 0.4392766	total: 544ms	remaining: 3.11s
136:	learn: 0.4378597	total: 548ms	remaining: 3.11s
137:	learn: 0.4369692	total: 551ms	remaining: 3.1s
138:	learn: 0.4362919	total: 555ms	remaining: 3.09s
139:	learn: 0.4356182	total: 558ms	remaining: 3.09s
140:	learn: 0.4347750	total: 562ms	remaining: 3.08s
141:	learn: 0.4341591	total: 566ms	remaining: 3.08s
142:	learn: 0.4333717	total: 570ms	remaining: 3.07s
143:	learn: 0.4329981	total: 573ms	remaining: 3.06s
144:	learn: 0.4322695	total: 577ms	remaining: 3.06s
145:	learn: 0.4313851	total: 580ms	remaining: 3.05s
146:	learn: 0.4306448	total: 584ms	remaining: 3.05s
147:	learn: 0.4298635	total: 587ms	remaining: 3.04s
148:	learn: 0.4288788	total: 591ms	remaining: 3.03s
149:	learn: 0.4272519	total: 594ms	remaining: 3.03s
150:	learn: 0.4264797	total: 598ms	remaining: 3.02s
151:	learn: 0.4259264	total: 602ms	remaining: 3.02s
152:	learn: 0.4254677	total: 605ms	remaining: 3.01s
153:	learn: 0.4244873	total: 609ms	remaining: 3.01s
154:	learn: 0.4236507	total: 613ms	remaining: 3s
155:	learn: 0.4229235	total: 616ms	remaining: 2.99s
156:	learn: 0.4211627	total: 620ms	remaining: 2.99s
157:	learn: 0.4206041	total: 624ms	remaining: 2.99s
158:	learn: 0.4200525	total: 628ms	remaining: 2.98s
159:	learn: 0.4196551	total: 632ms	remaining: 2.98s
160:	learn: 0.4192463	total: 636ms	remaining: 2.98s
161:	learn: 0.4181158	total: 640ms	remaining: 2.97s
162:	learn: 0.4171431	total: 643ms	remaining: 2.96s
163:	learn: 0.4161668	total: 647ms	remaining: 2.96s
164:	learn: 0.4152907	total: 650ms	remaining: 2.95s
165:	learn: 0.4146299	total: 654ms	remaining: 2.95s
166:	learn: 0.4136274	total: 658ms	remaining: 2.94s
167:	learn: 0.4132424	total: 661ms	remaining: 2.94s
168:	learn: 0.4123047	total: 665ms	remaining: 2.93s
169:	learn: 0.4116370	total: 669ms	remaining: 2.93s
170:	learn: 0.4107951	total: 672ms	remaining: 2.92s
171:	learn: 0.4093849	total: 676ms	remaining: 2.92s
172:	learn: 0.4090027	total: 680ms	remaining: 2.91s
173:	learn: 0.4084948	total: 683ms	remaining: 2.9s
174:	learn: 0.4078945	total: 687ms	remaining: 2.9s
175:	learn: 0.4073389	total: 691ms	remaining: 2.9s
176:	learn: 0.4064021	total: 695ms	remaining: 2.89s
177:	learn: 0.4057447	total: 699ms	remaining: 2.89s
178:	learn: 0.4050431	total: 703ms	remaining: 2.88s
179:	learn: 0.4046304	total: 707ms	remaining: 2.88s
180:	learn: 0.4043039	total: 711ms	remaining: 2.88s
181:	learn: 0.4037313	total: 714ms	remaining: 2.87s
182:	learn: 0.4031260	total: 718ms	remaining: 2.87s
183:	learn: 0.4026443	total: 721ms	remaining: 2.86s
184:	learn: 0.4019045	total: 725ms	remaining: 2.86s
185:	learn: 0.4011339	total: 728ms	remaining: 2.85s
186:	learn: 0.4006248	total: 732ms	remaining: 2.85s
187:	learn: 0.3999379	total: 736ms	remaining: 2.84s
188:	learn: 0.3995548	total: 740ms	remaining: 2.84s
189:	learn: 0.3989172	total: 744ms	remaining: 2.83s
190:	learn: 0.3985540	total: 748ms	remaining: 2.83s
191:	learn: 0.3977091	total: 751ms	remaining: 2.83s
192:	learn: 0.3968251	total: 755ms	remaining: 2.82s
193:	learn: 0.3962496	total: 759ms	remaining: 2.82s
194:	learn: 0.3956415	total: 763ms	remaining: 2.81s
195:	learn: 0.3953074	total: 767ms	remaining: 2.81s
196:	learn: 0.3948207	total: 770ms	remaining: 2.8s
197:	learn: 0.3942145	total: 774ms	remaining: 2.8s
198:	learn: 0.3932776	total: 778ms	remaining: 2.79s
199:	learn: 0.3927086	total: 781ms	remaining: 2.79s
200:	learn: 0.3916736	total: 785ms	remaining: 2.79s
201:	learn: 0.3911266	total: 789ms	remaining: 2.78s
202:	learn: 0.3901950	total: 793ms	remaining: 2.78s
203:	learn: 0.3891823	total: 797ms	remaining: 2.77s
204:	learn: 0.3886798	total: 801ms	remaining: 2.77s
205:	learn: 0.3880586	total: 804ms	remaining: 2.76s
206:	learn: 0.3872801	total: 807ms	remaining: 2.76s
207:	learn: 0.3867405	total: 811ms	remaining: 2.75s
208:	learn: 0.3860884	total: 815ms	remaining: 2.75s
209:	learn: 0.3856842	total: 818ms	remaining: 2.74s
210:	learn: 0.3854119	total: 822ms	remaining: 2.74s
211:	learn: 0.3844452	total: 826ms	remaining: 2.73s
212:	learn: 0.3841262	total: 830ms	remaining: 2.73s
213:	learn: 0.3833665	total: 834ms	remaining: 2.73s
214:	learn: 0.3827442	total: 838ms	remaining: 2.73s
215:	learn: 0.3823348	total: 842ms	remaining: 2.72s
216:	learn: 0.3818620	total: 845ms	remaining: 2.71s
217:	learn: 0.3812258	total: 849ms	remaining: 2.71s
218:	learn: 0.3806321	total: 853ms	remaining: 2.71s
219:	learn: 0.3802551	total: 857ms	remaining: 2.7s
220:	learn: 0.3798584	total: 861ms	remaining: 2.7s
221:	learn: 0.3796225	total: 864ms	remaining: 2.69s
222:	learn: 0.3788088	total: 868ms	remaining: 2.69s
223:	learn: 0.3783128	total: 871ms	remaining: 2.68s
224:	learn: 0.3776281	total: 875ms	remaining: 2.68s
225:	learn: 0.3772855	total: 878ms	remaining: 2.67s
226:	learn: 0.3765635	total: 882ms	remaining: 2.67s
227:	learn: 0.3758984	total: 885ms	remaining: 2.66s
228:	learn: 0.3752594	total: 889ms	remaining: 2.66s
229:	learn: 0.3747389	total: 893ms	remaining: 2.65s
230:	learn: 0.3741069	total: 897ms	remaining: 2.65s
231:	learn: 0.3733756	total: 900ms	remaining: 2.65s
232:	learn: 0.3730016	total: 904ms	remaining: 2.64s
233:	learn: 0.3721576	total: 907ms	remaining: 2.64s
234:	learn: 0.3714731	total: 911ms	remaining: 2.63s
235:	learn: 0.3711966	total: 914ms	remaining: 2.63s
236:	learn: 0.3700402	total: 918ms	remaining: 2.62s
237:	learn: 0.3694555	total: 922ms	remaining: 2.62s
238:	learn: 0.3689822	total: 925ms	remaining: 2.61s
239:	learn: 0.3682044	total: 929ms	remaining: 2.61s
240:	learn: 0.3674131	total: 932ms	remaining: 2.6s
241:	learn: 0.3668988	total: 936ms	remaining: 2.6s
242:	learn: 0.3662617	total: 940ms	remaining: 2.59s
243:	learn: 0.3655507	total: 943ms	remaining: 2.59s
244:	learn: 0.3650604	total: 947ms	remaining: 2.58s
245:	learn: 0.3645516	total: 951ms	remaining: 2.58s
246:	learn: 0.3641332	total: 955ms	remaining: 2.58s
247:	learn: 0.3636364	total: 959ms	remaining: 2.58s
248:	learn: 0.3633369	total: 963ms	remaining: 2.57s
249:	learn: 0.3626576	total: 967ms	remaining: 2.57s
250:	learn: 0.3618208	total: 970ms	remaining: 2.56s
251:	learn: 0.3613089	total: 974ms	remaining: 2.56s
252:	learn: 0.3608533	total: 978ms	remaining: 2.55s
253:	learn: 0.3603217	total: 982ms	remaining: 2.55s
254:	learn: 0.3595809	total: 986ms	remaining: 2.55s
255:	learn: 0.3586777	total: 991ms	remaining: 2.55s
256:	learn: 0.3583909	total: 996ms	remaining: 2.54s
257:	learn: 0.3576257	total: 999ms	remaining: 2.54s
258:	learn: 0.3570435	total: 1s	remaining: 2.54s
259:	learn: 0.3566764	total: 1.01s	remaining: 2.53s
260:	learn: 0.3563458	total: 1.01s	remaining: 2.53s
261:	learn: 0.3560401	total: 1.01s	remaining: 2.53s
262:	learn: 0.3555293	total: 1.02s	remaining: 2.52s
263:	learn: 0.3547855	total: 1.02s	remaining: 2.52s
264:	learn: 0.3542857	total: 1.03s	remaining: 2.52s
265:	learn: 0.3538006	total: 1.03s	remaining: 2.51s
266:	learn: 0.3533060	total: 1.03s	remaining: 2.51s
267:	learn: 0.3526939	total: 1.04s	remaining: 2.5s
268:	learn: 0.3519877	total: 1.04s	remaining: 2.5s
269:	learn: 0.3517537	total: 1.04s	remaining: 2.49s
270:	learn: 0.3508080	total: 1.05s	remaining: 2.49s
271:	learn: 0.3500259	total: 1.05s	remaining: 2.49s
272:	learn: 0.3497653	total: 1.06s	remaining: 2.48s
273:	learn: 0.3492508	total: 1.06s	remaining: 2.48s
274:	learn: 0.3483981	total: 1.06s	remaining: 2.47s
275:	learn: 0.3477770	total: 1.07s	remaining: 2.47s
276:	learn: 0.3473623	total: 1.07s	remaining: 2.47s
277:	learn: 0.3468938	total: 1.08s	remaining: 2.46s
278:	learn: 0.3462332	total: 1.08s	remaining: 2.46s
279:	learn: 0.3454977	total: 1.08s	remaining: 2.45s
280:	learn: 0.3448076	total: 1.09s	remaining: 2.45s
281:	learn: 0.3443516	total: 1.09s	remaining: 2.45s
282:	learn: 0.3438452	total: 1.09s	remaining: 2.44s
283:	learn: 0.3433907	total: 1.1s	remaining: 2.44s
284:	learn: 0.3425988	total: 1.1s	remaining: 2.43s
285:	learn: 0.3419951	total: 1.11s	remaining: 2.43s
286:	learn: 0.3415096	total: 1.11s	remaining: 2.43s
287:	learn: 0.3412078	total: 1.11s	remaining: 2.42s
288:	learn: 0.3407043	total: 1.12s	remaining: 2.42s
289:	learn: 0.3403454	total: 1.12s	remaining: 2.41s
290:	learn: 0.3394518	total: 1.13s	remaining: 2.41s
291:	learn: 0.3387511	total: 1.13s	remaining: 2.4s
292:	learn: 0.3383081	total: 1.13s	remaining: 2.4s
293:	learn: 0.3378192	total: 1.14s	remaining: 2.4s
294:	learn: 0.3374525	total: 1.14s	remaining: 2.39s
295:	learn: 0.3367306	total: 1.14s	remaining: 2.39s
296:	learn: 0.3364372	total: 1.15s	remaining: 2.38s
297:	learn: 0.3358281	total: 1.15s	remaining: 2.38s
298:	learn: 0.3353295	total: 1.15s	remaining: 2.38s
299:	learn: 0.3348945	total: 1.16s	remaining: 2.37s
300:	learn: 0.3343598	total: 1.16s	remaining: 2.37s
301:	learn: 0.3338656	total: 1.17s	remaining: 2.36s
302:	learn: 0.3335659	total: 1.17s	remaining: 2.36s
303:	learn: 0.3331049	total: 1.17s	remaining: 2.35s
304:	learn: 0.3327416	total: 1.18s	remaining: 2.35s
305:	learn: 0.3320349	total: 1.18s	remaining: 2.35s
306:	learn: 0.3317914	total: 1.18s	remaining: 2.34s
307:	learn: 0.3313384	total: 1.19s	remaining: 2.34s
308:	learn: 0.3307513	total: 1.19s	remaining: 2.33s
309:	learn: 0.3300265	total: 1.2s	remaining: 2.33s
310:	learn: 0.3295938	total: 1.2s	remaining: 2.32s
311:	learn: 0.3289511	total: 1.2s	remaining: 2.32s
312:	learn: 0.3285270	total: 1.21s	remaining: 2.31s
313:	learn: 0.3278740	total: 1.21s	remaining: 2.31s
314:	learn: 0.3275992	total: 1.21s	remaining: 2.31s
315:	learn: 0.3273663	total: 1.22s	remaining: 2.31s
316:	learn: 0.3268100	total: 1.22s	remaining: 2.3s
317:	learn: 0.3263983	total: 1.23s	remaining: 2.3s
318:	learn: 0.3260045	total: 1.23s	remaining: 2.29s
319:	learn: 0.3256108	total: 1.23s	remaining: 2.29s
320:	learn: 0.3251706	total: 1.24s	remaining: 2.29s
321:	learn: 0.3248142	total: 1.24s	remaining: 2.28s
322:	learn: 0.3242766	total: 1.24s	remaining: 2.28s
323:	learn: 0.3237997	total: 1.25s	remaining: 2.27s
324:	learn: 0.3235569	total: 1.25s	remaining: 2.27s
325:	learn: 0.3233061	total: 1.26s	remaining: 2.27s
326:	learn: 0.3228404	total: 1.26s	remaining: 2.26s
327:	learn: 0.3221715	total: 1.26s	remaining: 2.26s
328:	learn: 0.3218321	total: 1.27s	remaining: 2.25s
329:	learn: 0.3213528	total: 1.27s	remaining: 2.25s
330:	learn: 0.3210216	total: 1.27s	remaining: 2.24s
331:	learn: 0.3207933	total: 1.28s	remaining: 2.24s
332:	learn: 0.3203309	total: 1.28s	remaining: 2.24s
333:	learn: 0.3200375	total: 1.29s	remaining: 2.23s
334:	learn: 0.3196906	total: 1.29s	remaining: 2.23s
335:	learn: 0.3192856	total: 1.29s	remaining: 2.22s
336:	learn: 0.3188466	total: 1.3s	remaining: 2.22s
337:	learn: 0.3184269	total: 1.3s	remaining: 2.22s
338:	learn: 0.3181173	total: 1.3s	remaining: 2.21s
339:	learn: 0.3175417	total: 1.31s	remaining: 2.21s
340:	learn: 0.3173626	total: 1.31s	remaining: 2.2s
341:	learn: 0.3170251	total: 1.31s	remaining: 2.2s
342:	learn: 0.3163405	total: 1.32s	remaining: 2.2s
343:	learn: 0.3160132	total: 1.32s	remaining: 2.19s
344:	learn: 0.3157856	total: 1.33s	remaining: 2.19s
345:	learn: 0.3155249	total: 1.33s	remaining: 2.18s
346:	learn: 0.3151445	total: 1.33s	remaining: 2.18s
347:	learn: 0.3147092	total: 1.34s	remaining: 2.18s
348:	learn: 0.3143213	total: 1.34s	remaining: 2.17s
349:	learn: 0.3140159	total: 1.35s	remaining: 2.17s
350:	learn: 0.3137351	total: 1.35s	remaining: 2.17s
351:	learn: 0.3132810	total: 1.35s	remaining: 2.16s
352:	learn: 0.3128445	total: 1.36s	remaining: 2.16s
353:	learn: 0.3125474	total: 1.36s	remaining: 2.15s
354:	learn: 0.3123401	total: 1.37s	remaining: 2.15s
355:	learn: 0.3117150	total: 1.37s	remaining: 2.15s
356:	learn: 0.3113795	total: 1.38s	remaining: 2.15s
357:	learn: 0.3107638	total: 1.38s	remaining: 2.14s
358:	learn: 0.3104933	total: 1.38s	remaining: 2.14s
359:	learn: 0.3102088	total: 1.39s	remaining: 2.13s
360:	learn: 0.3099363	total: 1.39s	remaining: 2.13s
361:	learn: 0.3096367	total: 1.39s	remaining: 2.13s
362:	learn: 0.3091618	total: 1.4s	remaining: 2.12s
363:	learn: 0.3087256	total: 1.4s	remaining: 2.12s
364:	learn: 0.3083935	total: 1.41s	remaining: 2.11s
365:	learn: 0.3081259	total: 1.41s	remaining: 2.11s
366:	learn: 0.3074137	total: 1.41s	remaining: 2.11s
367:	learn: 0.3072116	total: 1.42s	remaining: 2.1s
368:	learn: 0.3069394	total: 1.42s	remaining: 2.1s
369:	learn: 0.3065296	total: 1.43s	remaining: 2.1s
370:	learn: 0.3062926	total: 1.43s	remaining: 2.09s
371:	learn: 0.3055785	total: 1.43s	remaining: 2.09s
372:	learn: 0.3052570	total: 1.44s	remaining: 2.08s
373:	learn: 0.3047833	total: 1.44s	remaining: 2.08s
374:	learn: 0.3042460	total: 1.44s	remaining: 2.08s
375:	learn: 0.3038481	total: 1.45s	remaining: 2.07s
376:	learn: 0.3036243	total: 1.45s	remaining: 2.07s
377:	learn: 0.3031716	total: 1.45s	remaining: 2.06s
378:	learn: 0.3023167	total: 1.46s	remaining: 2.06s
379:	learn: 0.3018409	total: 1.46s	remaining: 2.06s
380:	learn: 0.3016258	total: 1.47s	remaining: 2.05s
381:	learn: 0.3014093	total: 1.47s	remaining: 2.05s
382:	learn: 0.3012310	total: 1.47s	remaining: 2.04s
383:	learn: 0.3009777	total: 1.48s	remaining: 2.04s
384:	learn: 0.3005316	total: 1.48s	remaining: 2.04s
385:	learn: 0.3000362	total: 1.49s	remaining: 2.03s
386:	learn: 0.2997134	total: 1.49s	remaining: 2.03s

In [28]:
with open('model/project2.dat', 'wb') as fp :
    pickle.dump(best_model, fp)
    pickle.dump(scaler1, fp)